AMREX_HOME ?= ../../amrex_fork
AMREX_HYDRO_HOME ?= ../../AMReX-Hydro
TOP = ..

EBASE = incflo

BL_NO_FORT = TRUE

DIM = 2

PRECISION  = DOUBLE

TINY_PROFILE = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE
USE_CUDA   = TRUE

USE_HYPRE = FALSE

USE_EB = TRUE

USE_CSG = FALSE

include ../src/Make.incflo
